### ISSUE TITLE
Longest match only dictionary match

### ISSUE THREAD

**Issue by edoughty** [HazyResearch/ddlite#115] opened 2016-04-08 18:52 UTC
For a given dictionary, only create match the longest phrases and exclude all matching subphrases. Some dictionaries have inherent structure in the naming scheme and we don't want to create subphrases in all matched phrases. For example in a dictionary of all bacteria names, we'd have genus, genus species, etc. When we match "Yersinia pestis", we don't want to also match "Yersinia" in that same matched phrases in the sentence (Yersinia is the genus and is a separate entry in the dictionary).

**Comment by henryre** [comment] 2016-04-08 19:18
Duplicate of #95. Closing!

**Closed by henryre** 2016-04-08 19:18 UTC
Labels: duplicate
