### ISSUE TITLE
More parsing issues

### ISSUE THREAD

**Issue by jason-fries** [HazyResearch/ddlite#104] opened 2016-04-08 02:00 UTC
**UPDATE: Checking lxml to see if there is some weirdness going on -- I might be able to fix things.**

More parsing weirdness using the latest version of ddlite. Parsing a subset of the PMC corpus results in 
this error (I've attached the offending file). The XML itself is well-formed. 

`Traceback (most recent call last):
  File "/Users/fries/Code/dd-biolib/examples/pmc_corpus_demo.py", line 21, in <module>
    candidates = Entities(sentences, matcher)
  File "/Users/fries/Code/dd-biolib/ddlite/ddlite.py", line 279, in __init__
    super(Entities, self).__init__(content)
  File "/Users/fries/Code/dd-biolib/ddlite/ddlite.py", line 126, in __init__
    self._candidates = list(self._extract_candidates(C))
  File "/Users/fries/Code/dd-biolib/ddlite/ddlite.py", line 147, in _extract_candidates
    for cand in self._apply(sent):
  File "/Users/fries/Code/dd-biolib/ddlite/ddlite.py", line 285, in _apply
    xt = corenlp_to_xmltree(sent)
  File "/Users/fries/Code/dd-biolib/ddlite/tree_structs.py", line 88, in corenlp_to_xmltree
    root = corenlp_to_xmltree_sub(s, dep_parents, 0)
  File "/Users/fries/Code/dd-biolib/ddlite/tree_structs.py", line 121, in corenlp_to_xmltree_sub
    root.append(corenlp_to_xmltree_sub(s, dep_parents, i+1))
  File "/Users/fries/Code/dd-biolib/ddlite/tree_structs.py", line 118, in corenlp_to_xmltree_sub
    root = et.Element('node', attrib=attrib)
  File "src/lxml/lxml.etree.pyx", line 2998, in lxml.etree.Element (src/lxml/lxml.etree.c:80597)
  File "src/lxml/apihelpers.pxi", line 135, in lxml.etree._makeElement (src/lxml/lxml.etree.c:17594)
  File "src/lxml/apihelpers.pxi", line 123, in lxml.etree._makeElement (src/lxml/lxml.etree.c:17442)
  File "src/lxml/apihelpers.pxi", line 305, in lxml.etree._initNodeAttributes (src/lxml/lxml.etree.c:19976)
  File "src/lxml/apihelpers.pxi", line 316, in lxml.etree._addAttributeToNode (src/lxml/lxml.etree.c:20186)
  File "src/lxml/apihelpers.pxi", line 1439, in lxml.etree._utf8 (src/lxml/lxml.etree.c:32431)
ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters`

[Arthritis_2012_Jul_25_2012_943156.nxml.zip](https://github.com/HazyResearch/ddlite/files/209502/Arthritis_2012_Jul_25_2012_943156.nxml.zip)

**Comment by henryre** [comment] 2016-04-08 03:35
@jason-fries Since this is just for the features and cool parse visualizations, we can always just filter out the wonky characters. Let me know after you check it out

**Comment by henryre** [comment] 2016-04-08 03:37
Also @jason-fries, if these parse issues weren't happening before for the same input, my only guess is that the switch to JSON output for CoreNLP is the cause

**Comment by jason-fries** [comment] 2016-04-08 05:58
Okay -- so this issue isn't lxml and unicode. Carefully transforming all input to unicode still results in the problem above. If we strip offending characters and convert to ASCII we get some recursion errors. Any ideas?

Traceback (most recent call last):
  File "/Users/fries/Code/dd-biolib/examples/pmc_corpus_demo.py", line 28, in <module>
    candidates = Entities(sentences, matcher)
  File "/Users/fries/Code/dd-biolib/ddlite/ddlite.py", line 279, in __init__
    super(Entities, self).__init__(content)
  File "/Users/fries/Code/dd-biolib/ddlite/ddlite.py", line 126, in __init__
    self._candidates = list(self._extract_candidates(C))
  File "/Users/fries/Code/dd-biolib/ddlite/ddlite.py", line 147, in _extract_candidates
    for cand in self._apply(sent):
  File "/Users/fries/Code/dd-biolib/ddlite/ddlite.py", line 285, in _apply

**... WE MUST GO DEEPER .. ... INCEPTION BWAAAAHHH ....**

 File "/Users/fries/Code/dd-biolib/ddlite/tree_structs.py", line 121, in corenlp_to_xmltree_sub
    root.append(corenlp_to_xmltree_sub(s, dep_parents, i+1))
  File "/Users/fries/Code/dd-biolib/ddlite/tree_structs.py", line 111, in corenlp_to_xmltree_sub
    attrib[singular(k)] = ''.join(c for c in content if ord(c) < 128)
  File "/Users/fries/Code/dd-biolib/ddlite/tree_structs.py", line 126, in singular
    return re.sub(r'e?s$', '', s, flags=re.I)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 235, in _compile
    cachekey = (type(key[0]),) + key
RuntimeError: maximum recursion depth exceeded while calling a Python object

**Comment by jason-fries** [comment] 2016-04-08 07:16
More info -- the problem is two fold: some PMC documents have bad characters (NULLs \x00), which we just strip out; the other problem is that PMC text often includes tables which aren't properly marked up in XML. These spans seem to trip up CoreNLP and create really long sentences. This is turn causes recursion problems for serialization. So should we had a MAX_SENTENCE_LEN to the Parser object?

**Comment by ajratner** [comment] 2016-04-08 07:23
In the short term can we just use the subset of the docs that don't have
any of these errors?

**Comment by jason-fries** [comment] 2016-04-08 07:41
I think I've got something put together that works. Rather than identifying the subset of back actors and removing those files, i just drop any sentence containing more than 100 words after parsing. So far this + stripping out control characters solves the matching and serialization problems.

**Comment by henryre** [comment] 2016-04-08 15:44
Closing this for now. The issue seems to be with tables parsed as sentences. Right now, it doesn't make sense to engineer a clever ddlite utility to catch them before parsing. Once parsed, tables can be removed by thresholding the sentence length as @jason-fries suggested above.

**Closed by henryre** 2016-04-08 15:44 UTC
Labels: bug

**Comment by ajratner** [comment] 2016-04-08 17:01
My bad for missing this- let's come back to this, this is definitely tables (in my experience) and we should catch them once we can parse them, hopefully soon :)
